[workspace]
members = ["example_pkgs/*", "ndeq_linalg", "ndeq_num", "ndeq_ode"]

[workspace.package]
authors = ["Nossie531"]
edition = "2024"
repository = "https://github.com/nossie531/ndeq"
license = "MIT OR Apache-2.0"

[workspace.dependencies]
ndeq_linalg = { version = "=0.1.0", path = "ndeq_linalg" }
ndeq_num = { version = "=0.1.0", path = "ndeq_num" }
ndeq_ode = { version = "=0.1.0", path = "ndeq_ode" }
ndeq = { version = "=0.1.0", path = "." }

[package]
name = "ndeq"
version = "0.1.0"
description = "Network diffusion simulator."
keywords = ["diffusion equation", "network"]
categories = ["science", "simulation"]
authors.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
ndeq_linalg = { workspace = true }
ndeq_ode = { workspace = true }
