[package]
name = "sample"
edition.workspace = true
publish = false

[dependencies]
ndeq = { version = "0.1", path = "../../" }
plotters = "0.3"
plotters-backend = "0.3"
easy_node = "0.3"
ref_iter = "0.1"
